export const ERROR_HTTP = {
  VALIDATION_ERROR: 400,
  INVALID_JSON: 400,
  TENANT_REQUIRED: 400,
  PASSWORD_POLICY: 400,
  ORG_MOVE_INVALID_PARENT: 400,
  ORG_MOVE_DIVISION_REQUIRED: 400,
  ENROLLMENT_NOT_READY: 400,
  IDEMPOTENCY_KEY_REQUIRED: 400,
  AUTH_MISSING_TOKEN: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_TOKEN_INVALID: 401,
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_REFRESH_INVALID: 401,
  AUTH_REFRESH_EXPIRED: 401,
  AUTH_REFRESH_REUSE: 401,
  AUTH_PRINCIPAL_INVALID: 401,
  AUTH_ACCOUNT_LOCKED: 403,
  AUTH_ACCOUNT_SUSPENDED: 403,
  AUTH_ORG_SUSPENDED: 403,
  RBAC_FORBIDDEN: 403,
  RBAC_SCOPE_MISSING: 403,
  RBAC_SCOPE_VIOLATION: 403,
  ORG_MOVE_CROSS_TENANT: 403,
  NOT_FOUND: 404,
  ORGANIZATION_NOT_FOUND: 404,
  ORG_MOVE_NODE_NOT_FOUND: 404,
  ORG_MOVE_TARGET_NOT_FOUND: 404,
  CONFLICT_UNIQUE: 409,
  CONFLICT_FK: 409,
  ORGANIZATION_SLUG_TAKEN: 409,
  AUTH_EMAIL_TAKEN: 409,
  DIVISION_HAS_CHILDREN: 409,
  DEPARTMENT_HAS_TEAMS: 409,
  TEAM_HAS_USERS: 409,
  LAST_ORG_ADMIN: 409,
  COURSE_NO_LESSONS: 409,
  COURSE_NOT_PUBLISHED: 409,
  COURSE_HAS_ACTIVE_ENROLLMENTS: 409,
  COURSE_ARCHIVED: 409,
  COURSE_NOT_YET_AVAILABLE: 409,
  COURSE_NO_LONGER_AVAILABLE: 409,
  COURSE_PREREQUISITES_NOT_MET: 409,
  LESSON_PREREQUISITE_NOT_MET: 409,
  LESSON_COMPLETION_NOT_READY: 409,
  REGISTRATION_DISABLED: 403,
  PRE_ASSESSMENT_REQUIRED: 409,
  ASSESSMENT_EXISTS: 409,
  ASSESSMENT_KIND_EXISTS: 409,
  ASSESSMENT_MAX_ATTEMPTS: 409,
  ASSESSMENT_EXPIRED: 409,
  ASSESSMENT_ATTEMPT_IN_PROGRESS: 409,
  PATH_NOT_PUBLISHED: 409,
  ORG_TREE_STALE: 409,
  TX_WRITE_CONFLICT: 409,
  ORG_MOVE_SAME_PARENT: 409,
  RATE_LIMITED: 429,
  PAYLOAD_TOO_LARGE: 413,
  SERVICE_UNAVAILABLE: 503,
  INTERNAL_ERROR: 500,
} as const;

export type ErrorCode = keyof typeof ERROR_HTTP;

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  VALIDATION_ERROR: 'Request validation failed.',
  INVALID_JSON: 'Malformed JSON body.',
  TENANT_REQUIRED: 'organizationId query parameter is required.',
  PASSWORD_POLICY: 'Password does not meet policy requirements.',
  ORG_MOVE_INVALID_PARENT: 'The requested parent type is not allowed for this node.',
  ORG_MOVE_DIVISION_REQUIRED: 'A division is required when divisionless departments are disabled.',
  ENROLLMENT_NOT_READY: 'All lessons must be completed before starting or submitting the final assessment.',
  PRE_ASSESSMENT_REQUIRED: 'Complete the pre-assessment before accessing course lessons.',
  IDEMPOTENCY_KEY_REQUIRED: 'Idempotency-Key header is required.',
  AUTH_MISSING_TOKEN: 'Authorization bearer token is required.',
  AUTH_TOKEN_EXPIRED: 'Access token has expired.',
  AUTH_TOKEN_INVALID: 'Access token is invalid.',
  AUTH_INVALID_CREDENTIALS: 'Invalid email, organization, or password.',
  AUTH_REFRESH_INVALID: 'Refresh token is invalid.',
  AUTH_REFRESH_EXPIRED: 'Refresh token has expired.',
  AUTH_REFRESH_REUSE: 'Refresh token reuse detected. Please sign in again.',
  AUTH_PRINCIPAL_INVALID: 'Authenticated principal is no longer valid.',
  AUTH_ACCOUNT_LOCKED: 'Account is temporarily locked after too many failed attempts.',
  AUTH_ACCOUNT_SUSPENDED: 'This account has been suspended.',
  AUTH_ORG_SUSPENDED: 'This organization has been suspended.',
  RBAC_FORBIDDEN: 'You do not have permission to perform this action.',
  RBAC_SCOPE_MISSING: 'Manager scope requires a department assignment.',
  RBAC_SCOPE_VIOLATION: 'The target is outside your allowed scope.',
  ORG_MOVE_CROSS_TENANT: 'Cannot move nodes across organizations.',
  NOT_FOUND: 'Resource not found.',
  ORGANIZATION_NOT_FOUND: 'Organization not found.',
  ORG_MOVE_NODE_NOT_FOUND: 'The node to move was not found.',
  ORG_MOVE_TARGET_NOT_FOUND: 'The target parent was not found.',
  CONFLICT_UNIQUE: 'A unique constraint was violated.',
  CONFLICT_FK: 'A related record is missing or still in use.',
  ORGANIZATION_SLUG_TAKEN: 'This organization slug is already taken.',
  AUTH_EMAIL_TAKEN: 'This email is already in use in the organization.',
  DIVISION_HAS_CHILDREN: 'Division still has departments attached.',
  DEPARTMENT_HAS_TEAMS: 'Department still has teams attached.',
  TEAM_HAS_USERS: 'Team still has users attached.',
  LAST_ORG_ADMIN: 'Cannot remove or demote the last organization admin.',
  COURSE_NO_LESSONS: 'A course must have at least one lesson before publishing.',
  COURSE_NOT_PUBLISHED: 'Only published courses can be assigned.',
  COURSE_HAS_ACTIVE_ENROLLMENTS: 'Course has active enrollments.',
  COURSE_ARCHIVED: 'Archived courses are read-only. Unarchive to edit.',
  COURSE_NOT_YET_AVAILABLE: 'This course is not available yet.',
  COURSE_NO_LONGER_AVAILABLE: 'This course is no longer available.',
  COURSE_PREREQUISITES_NOT_MET: 'Complete required courses before starting this course.',
  LESSON_PREREQUISITE_NOT_MET: 'Complete the prerequisite lesson before continuing.',
  LESSON_COMPLETION_NOT_READY: 'This lesson is not ready to mark complete.',
  REGISTRATION_DISABLED: 'Public organization registration is disabled.',
  ASSESSMENT_EXISTS: 'This course already has an assessment.',
  ASSESSMENT_KIND_EXISTS: 'This course already has an assessment of this kind.',
  ASSESSMENT_MAX_ATTEMPTS: 'Maximum assessment attempts reached.',
  ASSESSMENT_EXPIRED: 'The assessment attempt has expired.',
  ASSESSMENT_ATTEMPT_IN_PROGRESS: 'An assessment attempt is already in progress.',
  PATH_NOT_PUBLISHED: 'Learning path is not published.',
  ORG_TREE_STALE: 'The organization tree has changed. Refresh and retry.',
  TX_WRITE_CONFLICT: 'The operation conflicted with another write. Retry.',
  ORG_MOVE_SAME_PARENT: 'Node is already under the requested parent.',
  RATE_LIMITED: 'Too many requests.',
  PAYLOAD_TOO_LARGE: 'Request body is too large.',
  SERVICE_UNAVAILABLE: 'Service is temporarily unavailable.',
  INTERNAL_ERROR: 'An unexpected error occurred.',
};
